package Network;

public enum NetworkCmd
{
    /**
     * Client -> Serveur
     **/
    CONNECTION,
    CREER_PARTIE,
    REJOINDRE_PARTIE,
    REJOINDRE_IMMEDIATEMENT,
    CHARGER_PARTIE,
    SAUVEGARDER_PARTIE,
    ENVOYER_COUP,
    ANNULER_COUP,
    ACCEPTER_ANNULER,
    REFAIRE_COUP,
    ACCEPTER_REFAIRE,
    REFUSER_ANNULER,
    REFUSER_REFAIRE,
    QUITTER_PARTIE,
    LISTER_PARTIE,
    DEMANDER_CONFIGURATION,

    /**
     * Serveur -> Client
     **/
    LOGIN_OK,
    LOGIN_BAD, 
    CREATION_OK,
    CREATION_MAUVAIS,
    NOUVEAU_JOUEUR,
    JOUEUR_QUITTE,
    REJOIN_OK,
    REJOIN_MAUVAIS,
    CHARGEMENT_OK,
    CHARGEMENT_MAUVAIS,
    SAUVEGARDER_OK,
    SAUVEGARDER_MAUVAIS,
    DEMANDER_COUP,
    COUP_MAUVAIS,
    COUP_OK,
    VEUT_ANNULER,
    VEUT_REFAIRE,
    DEMANDE_ANNULER_OK,
    DEMANDE_ANNULER_MAUVAIS,
    DACCORD_ANNULER,
    PARTIE_PRETE,
    LISTE_PARTIE,
    LANCER_PARTIE,
    NOUVELLE_CONFIGURATION,
    FIN_PARTIE,
    TOUR_JOUEUR,
    COUP_JOUEUR,

    /**
     * Communication Inter-Thread serveur
     **/
    
}
